[package]
name = "WikiScrape"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
